apiVersion: apps/v1
kind: Deployment
metadata:
  name: psql-itwl-dev-01
  namespace: keycloak
  labels: 
    app: psql 
spec:
  replicas: 1
  selector:
    matchLabels:  #Deploy in a POD that has labels app: color and color: blue
      app: psql
  template: #For the creation of the pod      
    metadata:
      labels:
        app: psql
      annotations:
        sidecar.istio.io/inject: "false"        
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432 
          envFrom:
            - configMapRef:
                name: postgresql-configmap       
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgdatavol
      volumes:
        - name: pgdatavol
          persistentVolumeClaim:
            claimName: pg-pvc