apiVersion: v1
kind: Service
metadata:
  name: tekton-dashboard-proxy
  namespace: k8s-proxy
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: tekton-dashboard-proxy
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tekton-dashboard-proxy
  namespace: k8s-proxy
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: tekton-auth.icnp.in-soft.co.kr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tekton-dashboard-proxy
            port:
              number: 3000
