apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgql-keycloak
  namespace: keycloak
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
